import { auth } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) {
  const { userId } = await auth();
  if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { id } = await params;

  const user = await prisma.user.findUnique({ where: { clerkId: userId } });
  if (!user) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const invoice = await prisma.invoice.findFirst({
    where: { id, deal: { userId: user.id } },
    include: { deal: true },
  });

  if (!invoice) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const issueDate = new Date(invoice.issuedDate).toLocaleDateString();
  const dueDate = invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString() : "N/A";
  const paidAt = invoice.paidAt ? new Date(invoice.paidAt).toLocaleDateString() : null;

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #111; padding: 60px; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 60px; }
    .brand { font-size: 28px; font-weight: 800; color: #7c3aed; }
    .invoice-label { font-size: 13px; color: #6b7280; text-transform: uppercase; letter-spacing: 1px; }
    .invoice-number { font-size: 22px; font-weight: 700; color: #111; margin-top: 4px; }
    .section { margin-bottom: 40px; }
    .section-title { font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #9ca3af; margin-bottom: 8px; }
    .value { font-size: 15px; color: #111; font-weight: 500; }
    .sub-value { font-size: 13px; color: #6b7280; margin-top: 2px; }
    .divider { border: none; border-top: 1px solid #f3f4f6; margin: 40px 0; }
    .amount-box { background: #f5f3ff; border-radius: 12px; padding: 30px; margin: 40px 0; }
    .amount-label { font-size: 13px; color: #7c3aed; margin-bottom: 8px; }
    .amount-value { font-size: 42px; font-weight: 800; color: #7c3aed; }
    .status-badge { display: inline-block; padding: 6px 16px; border-radius: 999px; font-size: 12px; font-weight: 600; margin-top: 12px; }
    .status-paid { background: #d1fae5; color: #065f46; }
    .status-unpaid { background: #fef3c7; color: #92400e; }
    .status-overdue { background: #fee2e2; color: #991b1b; }
    .meta-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 30px; }
    .footer { margin-top: 60px; text-align: center; font-size: 12px; color: #9ca3af; }
    .notes { background: #f9fafb; border-radius: 8px; padding: 16px; font-size: 14px; color: #374151; }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">BrandDesk</div>
    <div style="text-align: right;">
      <div class="invoice-label">Invoice</div>
      <div class="invoice-number">#${invoice.id.slice(-8).toUpperCase()}</div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Brand / Client</div>
    <div class="value">${invoice.deal.brandName}</div>
    <div class="sub-value">${invoice.deal.platform}</div>
  </div>

  <div class="amount-box">
    <div class="amount-label">Total Amount</div>
    <div class="amount-value">
      ${invoice.currency === "INR" ? "₹" : "$"}${Number(invoice.amount).toLocaleString()}
      <span style="font-size:20px;font-weight:400;margin-left:6px;">${invoice.currency}</span>
    </div>
    <div class="status-badge status-${invoice.status.toLowerCase()}">
      ${invoice.status}${paidAt ? ` · Paid on ${paidAt}` : ""}
    </div>
  </div>

  <div class="meta-grid">
    <div>
      <div class="section-title">Issue Date</div>
      <div class="value">${issueDate}</div>
    </div>
    <div>
      <div class="section-title">Due Date</div>
      <div class="value">${dueDate}</div>
    </div>
    <div>
      <div class="section-title">Deal Status</div>
      <div class="value">${invoice.deal.status}</div>
    </div>
  </div>

  ${invoice.notes ? `
  <hr class="divider">
  <div class="section">
    <div class="section-title">Notes</div>
    <div class="notes">${invoice.notes}</div>
  </div>
  ` : ""}

  <div class="footer">
    Generated by BrandDesk
  </div>
</body>
</html>
  `;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html",
      "Content-Disposition": `inline; filename="invoice-${invoice.id.slice(-8)}.html"`,
    },
  });
}